#!/usr/bin/env python3
"""Write a project's `utils/API.md` — what the shared utilities offer, not how.

A task that needs a helper has to find out what is already there. Reading the
modules works and is what the guides used to ask for, but it is expensive and
it grows: yoga's `utils/` went from nothing to 21.9 KB in a quarter of an hour,
and every task that so much as glanced at it paid for the whole thing. The
digest below is 11% of that — signatures, public constants, and the first line
of each docstring, never a function body.

It is generated rather than written by hand, because a hand-kept index drifts
from the code the moment someone edits a module and forgets. Nothing here is
imported: the source is parsed, so a module with a heavy import or a syntax
error costs nothing and cannot run anything.

    python -m dex.tools.utils_api assets/yoga      # write assets/yoga/utils/API.md
    python -m dex.tools.utils_api --all            # every project
    python -m dex.tools.utils_api --check assets/yoga   # stale? exit 1, write nothing
"""

from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

from ..config import CONFIG

HEADER = """<!-- Generated by `python -m dex.tools.utils_api`. Do not edit by hand:
     the next task to change a module regenerates this file and your edit is
     gone. Describe a utility in its docstring instead — that is what lands
     here. -->

# Shared utilities

What the modules in this directory offer. Signatures and one-line descriptions
only; open a module itself when this is not enough to use it.
"""


def _first_line(node: ast.AST) -> str:
    """The first line of a docstring, which is the whole description here."""
    doc = ast.get_docstring(node) or ""  # type: ignore[arg-type]
    return " ".join(doc.strip().split("\n")[0].split())


def _signature(node: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    returns = f" -> {ast.unparse(node.returns)}" if node.returns else ""
    return f"{node.name}({ast.unparse(node.args)}){returns}"


def describe(path: Path, skill: str = "") -> str:
    """One module's section: where it came from, its docstring, its exports."""
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    # Which skill provides it. `utils/` is materialised from several, and a
    # task that wants to add a function *beside* this one has to write to the
    # right skill — the brief lists the skills, this is what joins them to the
    # module names a reader actually has in hand.
    lines = [f"## `{path.stem}`" + (f" — from `{skill}`" if skill else "")]
    if summary := _first_line(tree):
        lines.append("")
        lines.append(summary)
    entries: list[str] = []
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            # A leading underscore means the module did not mean to offer it.
            if node.name.startswith("_"):
                continue
            entries.append(f"- `{_signature(node)}` — {_first_line(node)}")
        elif isinstance(node, ast.ClassDef) and not node.name.startswith("_"):
            entries.append(f"- `class {node.name}` — {_first_line(node)}")
        elif isinstance(node, ast.Assign):
            for target in node.targets:
                # Module-level SHOUTING is the convention for a public constant;
                # anything else is internal state and not worth a line here.
                if isinstance(target, ast.Name) and target.id.isupper():
                    if not target.id.startswith("_"):
                        entries.append(f"- `{target.id}` — constant")
    if entries:
        lines.append("")
        lines.extend(entries)
    return "\n".join(lines)


#: The guide opts in to an auto-maintained roster by carrying these markers.
#: Absent, the guide is left exactly as it is — a hand-edited file is never
#: guessed at.
ROSTER_BEGIN = "<!-- utils:begin -->"
ROSTER_END = "<!-- utils:end -->"

ROSTER_NOTE = (
    "<!-- Rows come from each module's first docstring line. Change the "
    "docstring, not the table. -->"
)


def summary(path: Path) -> str:
    """The one line that stands for a whole module in the roster."""
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    except SyntaxError:
        return "Could not be parsed."
    return _first_line(tree) or "No description — give the module a docstring."


def roster(utils_dir: Path) -> str:
    """The succinct table: one row per module, for the guide the task is given.

    This is what a task reads to decide whether anything here is worth a closer
    look; `API.md` is the closer look. It lives in the guide rather than on
    disk because the guide is already in every brief, so knowing what exists
    costs a task nothing at all.
    """
    modules = _modules(utils_dir)
    rows = "\n".join(f"| `{m.stem}` | {summary(m)} |" for m in modules)
    if not rows:
        rows = "| _(none yet)_ | |"
    return f"{ROSTER_BEGIN}\n{ROSTER_NOTE}\n\n| Module | What it does |\n|---|---|\n{rows}\n\n{ROSTER_END}"


def update_guide(project_dir: Path, check: bool = False) -> bool:
    """Refresh the roster inside the project's AGENTS.md. True when it changed."""
    guide = project_dir / "AGENTS.md"
    if not guide.exists():
        return False
    text = guide.read_text(encoding="utf-8")
    start, end = text.find(ROSTER_BEGIN), text.find(ROSTER_END)
    if start == -1 or end == -1 or end < start:
        return False
    wanted = roster(project_dir / "utils")
    current = text[start : end + len(ROSTER_END)]
    if wanted == current:
        return False
    if not check:
        guide.write_text(text[:start] + wanted + text[end + len(ROSTER_END) :], encoding="utf-8")
    return True


def _modules(utils_dir: Path) -> list[Path]:
    if not utils_dir.is_dir():
        return []
    return sorted(
        p for p in utils_dir.glob("*.py") if p.stem != "__init__" and not p.stem.startswith("_")
    )


def _combined(project_dir: Path) -> str:
    """The project's index from its skills, or `""` if it has none."""
    try:
        from .. import skills

        workspace = project_dir.parent.parent
        enabled = skills.read_enabled(project_dir).skills
        parts = [
            (skill.name, skill.index.read_text(encoding="utf-8"))
            for skill in skills.all_skills(workspace)
            if enabled.get(skill.name) == skill.version and skill.index.is_file()
        ]
        return combine(parts)
    except Exception:
        return ""


def providers(project_dir: Path) -> dict[str, str]:
    """Which skill each materialised module came from, by filename.

    Best effort: an install mid-migration, or a module somebody dropped in by
    hand, simply has no entry and its section says nothing about a skill.
    """
    try:
        from .. import skills

        workspace = project_dir.parent.parent
        enabled = skills.read_enabled(project_dir).skills
        return {
            module.name: skill.name
            for skill in skills.all_skills(workspace)
            if enabled.get(skill.name) == skill.version
            for module in skill.modules()
        }
    except Exception:
        return {}


def render(utils_dir: Path, from_skill: dict[str, str] | None = None) -> str:
    """The whole file, or an empty string when there is nothing to describe."""
    modules = _modules(utils_dir)
    if not modules:
        return ""
    from_skill = from_skill or {}
    sections = []
    for path in modules:
        try:
            sections.append(describe(path, from_skill.get(path.name, "")))
        except SyntaxError as exc:
            # A half-written module must not take the index down with it.
            sections.append(f"## `{path.stem}`\n\nCould not be parsed ({exc.msg}).")
    return HEADER + "\n" + "\n\n".join(sections) + "\n"


def write(project_dir: Path, check: bool = False) -> bool:
    """Refresh the guide's roster and `<project>/utils/API.md`. True when either changed.

    Writes only on a real difference, so a task starting is not an asset event
    and the watcher stays quiet.
    """
    # The roster goes first: it is the thing in every brief, so it must be
    # right even for a project whose utils/ has just been emptied.
    changed = update_guide(project_dir, check=check)
    utils_dir = project_dir / "utils"
    if not utils_dir.is_dir():
        return changed
    target = utils_dir / "API.md"
    # Combined from the enabled skills' own indexes when there are any. Each
    # skill carries the index for its own modules, so a skill copied to another
    # install arrives already describing itself; scanning the materialised
    # directory is the fallback for a project whose utils/ came from somewhere
    # else, or an install mid-migration.
    wanted = _combined(project_dir) or render(utils_dir, providers(project_dir))
    current = target.read_text(encoding="utf-8") if target.exists() else ""
    if wanted == current:
        return changed
    if not wanted:
        # Every module went away; the index should not outlive them.
        if not check:
            target.unlink(missing_ok=True)
        return True
    if not check:
        target.write_text(wanted, encoding="utf-8")
    return True


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("project", nargs="*", type=Path, help="project directory")
    parser.add_argument("--all", action="store_true", help="every project under the assets root")
    parser.add_argument(
        "--check", action="store_true", help="report staleness, write nothing; exit 1 if stale"
    )
    args = parser.parse_args(argv)

    projects = list(args.project)
    if args.all or not projects:
        projects = [p for p in sorted(CONFIG.assets_dir.iterdir()) if p.is_dir()]

    stale = []
    for project in projects:
        if write(project, check=args.check):
            stale.append(project.name)
            print(f"{'stale' if args.check else 'wrote'}: {project / 'utils' / 'API.md'}")
    if not stale:
        print("up to date")
    return 1 if (args.check and stale) else 0


if __name__ == "__main__":
    sys.exit(main())


# --------------------------------------------------- one index per skill


def render_skill(utils_dir: Path) -> str:
    """One skill's index: its own modules, with no attribution.

    Inside a skill there is nothing to attribute to — every module in it came
    from it. The skill name is added when these are combined, which is also
    the only place it can be right: a skill can be renamed, and an index that
    had baked the old name in would then be lying.
    """
    modules = _modules(utils_dir)
    sections = []
    for path in modules:
        try:
            sections.append(describe(path))
        except SyntaxError as exc:
            sections.append(f"## `{path.stem}`\n\nCould not be parsed ({exc.msg}).")
    return "\n\n".join(sections)


def combine(parts: list[tuple[str, str]]) -> str:
    """The project's index, from each enabled skill's own.

    `parts` is `(skill name, that skill's index)`, in enable order. Combined
    rather than regenerated from the materialised directory, so a skill carries
    its own index and arrives at another install already describing itself.

    The skill name goes into each heading here, because `utils/` is a flat
    import namespace — `from utils import rig` does not say where `rig` came
    from, and a task promoting a helper beside it has to know.
    """
    sections = []
    for skill, body in parts:
        if not body.strip():
            continue
        sections.append(
            "\n".join(
                f"{line} — from `{skill}`" if line.startswith("## `") else line
                for line in body.splitlines()
            )
        )
    if not sections:
        return ""
    return HEADER + "\n" + "\n\n".join(sections) + "\n"
